language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install codecov

script:
  - coverage run -a --source=. test_check_fonttools.py
  - pip install fonttools==2.5
  - coverage run -a --source=. test_check_fonttools.py
  - pip install -U fonttools
  - sh .coverage_run_all.sh
  - pip install brotli
  - sh .coverage_run_all.sh

after_success:
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
