language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage
  - pip install codacy-coverage
  - pip install codecov

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - coverage run -a --source=. tests/check_fonttools_test.py
  - pip install fonttools==2.5
  - coverage run -a --source=. tests/check_fonttools_test.py
  - pip install -U fonttools
  - sh tests/run_tests.sh
  - pip install brotli
  - sh tests/run_tests.sh

after_success:
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
